apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    name: api-config
data:
  ASPNETCORE_URLS: "http://+:9000"
  ASPNETCORE_ENVIRONMENT: "Development"
  CONNECTION_STRING: "Data Source=110.107.207.171, 1433;Initial Catalog=master;Persist Security Info=True;User ID=sa;Password=QL1Ty4AjK3kpLQXX;Trust Server Certificate=True"
