apiVersion: v1
kind: Service
metadata:
  name: sanduba-api-svc
  labels:
    app: sanduba-api-svc
spec:
  type: NodePort
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    app: sanduba-api-deployment