apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanduba-api-deployment
  labels:
    app: sanduba-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanduba-api-deployment
  template:
    metadata:
      labels:
        app: sanduba-api-deployment
    spec:
      containers:
        - name: restaurantesanduba-pod-api
          image: cangelosilima/restaurantesanduba.api:latest
          ports: 
            - containerPort: 9000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10