apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanduba-db-deployment
  labels:
    app: sanduba-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanduba-db-deployment
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: sanduba-db-deployment
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 10001
      containers:
        - name: sanduba-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "QL1Ty4AjK3kpLQXX"
            - name: MSSQL_DATA_DIR
              value: "/data"
            - name: MSSQL_LOG_DIR
              value: "/log"
          volumeMounts:
            - name: system
              mountPath: /var/opt/mssql
            - name: data
              mountPath: /data
            - name: log
              mountPath: /log
      volumes:
        - name: system
          persistentVolumeClaim:
            claimName: sanduba-db-pvc-system
        - name: data
          persistentVolumeClaim:
            claimName: sanduba-db-pvc-data
        - name: log
          persistentVolumeClaim:
            claimName: sanduba-db-pvc-log
