apiVersion: v1
kind: Service
metadata:
  name: sanduba-db-svc
spec:
  selector:
    app: sanduba-db-deployment
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 1433
      targetPort: 1433