name: Push to DockerHub

on:
  push:
    branches: [ "main", "develop", release ]
env:
  branch_name: ${GITHUB_REF##*/}
  image_tags:
        |
    if: $({ github.ref == 'refs/heads/main' }) type=raw,value={{date 'YYYY.MM'}}
    if: $({ github.ref == 'refs/heads/main' }) type=raw,value=latest
    if: $({ github.ref != 'refs/heads/main' }) type=raw,value=latest-$branch_name

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Add tags to image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/restaurantesanduba.api
          tags: |
            type=raw,value={{date 'YYYY.MM'}}
            type=raw,value=latest

      - name: Add tags to image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/restaurantesanduba.api
          tags: $image_tags

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./api/RestauranteSanduba/src
          file: ./api/RestauranteSanduba/src/api/Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
